### ISSUE TITLE
Solr / Lucene 7

### ISSUE THREAD

**Issue by garysieling** [DiceTechJobs/RelevancyFeedback#1]
I took at stab at upgrading to Solr 7 (https://github.com/DiceTechJobs/RelevancyFeedback/compare/master...garysieling:Solr.7.0.0).

I'm stuck on a change that removes "getBoost" and "setBoost", and was wondering if you had any insight on what the right change would be. 

Here is the ticket which appears to have made this change:
https://issues.apache.org/jira/browse/LUCENE-6819

Error:(163, 27) java: cannot find symbol
  symbol:   method getBoost()
  location: variable qry of type org.apache.lucene.search.Query
D:\projects\email-alerts\RelevancyFeedback\src\main\java\org\dice\solrenhancements\unsupervisedfeedback\UnsupervisedFeedback.java
Error:(728, 26) java: cannot find symbol
  symbol:   class PayloadScoreQuery
  location: class org.dice.solrenhancements.unsupervisedfeedback.UnsupervisedFeedback
Error:(738, 15) java: cannot find symbol
  symbol:   method setBoost(float)
  location: variable tq of type org.apache.lucene.search.TermQuery
Error:(776, 56) java: cannot find symbol
  symbol:   method getBoost()
  location: variable termQuery of type org.apache.lucene.search.Query
Error:(779, 46) java: cannot find symbol
  symbol:   method getBoost()
  location: variable termQuery of type org.apache.lucene.search.Query
Error:(781, 22) java: cannot find symbol
  symbol:   method setBoost(java.lang.Float)
  location: variable termQuery of type org.apache.lucene.search.Query
D:\projects\email-alerts\RelevancyFeedback\src\main\java\org\dice\solrenhancements\relevancyfeedback\RelevancyFeedbackHandler.java
Error:(252, 25) java: cannot find symbol
  symbol:   method getBoost()
  location: variable q of type org.apache.lucene.search.Query
Error:(305, 39) java: cannot find symbol
  symbol:   method getFacetCounts()
  location: variable f of type org.apache.solr.request.SimpleFacets
D:\projects\email-alerts\RelevancyFeedback\src\main\java\org\dice\solrenhancements\relevancyfeedback\RelevancyFeedback.java
Error:(989, 26) java: cannot find symbol
  symbol:   class PayloadTermQuery
  location: class org.dice.solrenhancements.relevancyfeedback.RelevancyFeedback
Error:(997, 19) java: cannot find symbol
  symbol:   method setBoost(float)
  location: variable tq of type org.apache.lucene.search.Query
Error:(1044, 57) java: cannot find symbol
  symbol:   method getBoost()
  location: variable termQuery of type org.apache.lucene.search.Query
Error:(1047, 47) java: cannot find symbol
  symbol:   method getBoost()
  location: variable termQuery of type org.apache.lucene.search.Query
Error:(1049, 22) java: cannot find symbol
  symbol:   method setBoost(java.lang.Float)
  location: variable termQuery of type org.apache.lucene.search.Query

**Comment by simonhughes22** [comment]
@garysieling sorry I didn't see this issue until now. Will look into shortly. I've fixed that before in 6.x IIRC.

**Comment by simonhughes22** [comment]
@garysieling I just created a 7.0 branch. Please check it out, and let me know if you have any issues. I did a major refactoring following the conference, so I was unable to merge your changes easily as too much has changed. The new version in the 7.0 branch should work.

**Comment by simonhughes22** [comment]
Confirmed works ok in 7.
